import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="bg-slate-900 text-white max-w-3xl mx-auto py-20 px-4 "
    >
      <body>{children}</body>
    </html>
  );
}
